export const ROUTES = {
  home: "/",
  plans: "/plans",
  planSize: "/plans/size",
  planFrequency: "/plans/frequency",
  buildBox: "/build-box",
  cart: "/cart",
  cartReview: "/cart-review",
  checkout: "/checkout",
  giftCheckout: "/gift-checkout",
  confirmation: "/confirmation",
  verifyPayment: "/verify-payment",
  dashboard: "/dashboard",
  auth: "/auth/signin",
  login: "/login",
  authSignIn: "/auth/signin",
  authSignUp: "/auth/signup",
  verificationEmailSent: "/email-sent",
  authVerifyEmail: "/verify-email",
  authResetPassword: "/reset-password",
  authAcceptInvitation: "/accept-invitation",
  products: "/products",
  howItWorks: "/how-it-works",
  sourcing: "/sourcing",
  farmLocator: "/farm-locator",
  faqs: "/faqs",
  club: "/club",
  about: "/about",
  contact: "/contact",
  reviews: "/reviews",
  gifts: "/gifts",
  giftCards: "/gift-cards",
  corporateGifting: "/corporate-gifting",

  // Admin routes
  adminLogin: "/admin/login",
  adminInvitationSetup: "/admin/invitation",
  admin: "/admin",
  adminOrders: "/admin/orders",
  adminCustomers: "/admin/customers",
  adminPlans: "/admin/plans",
  adminGifts: "/admin/gifts",
  addPlan: "/admin/add-plan",
  editPlan: "/admin/edit-plan/:planId",
  addGift: "/admin/add-gift",
  editGift: "/admin/edit-gift/:giftId",
  adminProducts: "/admin/products",
  adminSubscriptions: "/admin/subscriptions",
  adminDeliveries: "/admin/deliveries",
  adminContacts: "/admin/contacts",
  adminAnalytics: "/admin/analytics",
  adminSettings: "/admin/settings",
} as const;

export const buildProductRoute = (id: string): string => `/product/${id}`;
